name: AUTO Pull Request validation
on: [pull_request]
jobs:
  pr_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        name: Install Node 16
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Pre bootstrap archive tooltip package
        uses: actions/upload-artifact@v3
        with:
          name: tooltip-package-pre-bootstrap
          path: packages/ui-tooltip
      - name: Bootstrap project
        run: yarn bootstrap
      - name: After bootstrap archive tooltip package
        uses: actions/upload-artifact@v3
        with:
          name: tooltip-package-after-bootstrap
          path: packages/ui-tooltip
      - name: Calculate bundle size
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Before docs build archive tooltip package
        uses: actions/upload-artifact@v3
        with:
          name: tooltip-package-before-docs-build
          path: packages/ui-tooltip
      - name: Build docs-app
        run: yarn build:docs
      - name: Archive docs-build
        uses: actions/upload-artifact@v3
        with:
          name: docs-build
          path: packages/__docs__/__build__
      - name: Archive tooltip package
        uses: actions/upload-artifact@v3
        with:
          name: tooltip-package-before-preview-deploy
          path: packages/ui-tooltip
